version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      spring.datasource.url: jdbc:mysql://localhost:3306/employee_directory
    ports:
      - 3306:3306
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d